title:            myers.io
description:      Dale Myers' blog
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://myers.io

# Owner/author information
owner:
  name:           Dale Myers
  avatar:         bio-photo.jpg
  bio:            "A 5th Year Masters student in Informatics at the University of Edinburgh"
  email:          dale@myers.io
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        Vel0x
  facebook:       
  github:         Vel0x
  stackoverflow: 
  linkedin:       dalemmyers
  instagram:      
  lastfm:         
  tumblr: 
  pinterest: 
  foursquare: 
  steam: 
  dribbble: 
  # For Google Authorship https://plus.google.com/authorship
  google_plus: DaleMyers1

# Analytics and webmaster tools stuff goes here
google_analytics: UA-46471308-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Posts
    url: /posts/
  - title: "<i class=\"icon-feed\"></i>"
    url: /feed.xml
#  - title: Theme Setup
#    url: /theme-setup/
#  - title: Made Mistakes
#    url: http://mademistakes.com
#    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
highlighter:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:day/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
