title:            myers.io
description:      Dale Myers' blog
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://myers.io

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
highlighter:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:day/:title/

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

coderay:
  coderay_line_numbers: 
  coderay_line_numbers_start: 1
  coderay_tab_width: 4
  coderay_bold_every: 10
  coderay_css: class

# Site owner
owner:
  name: Dale Myers
  avatar: bio-photo.jpg
  bio: "Software Engineer at Microsoft, currently working on Office for iOS and OS X."
  email: contact@myers.io
  disqus-shortname:
  twitter: Vel0x
  facebook: #username
  google:
    plus: DaleMyers1
    analytics: UA-46471308-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: Vel0x 
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: dalemmyers
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
